# Generated by Django 3.2 on 2023-07-04 07:01

import api.service_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230704_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[api.service_functions.check_username], verbose_name='Имя пользователя'),
        ),
    ]
