# Generated by Django 3.2 on 2023-07-04 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230704_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
