# Generated by Django 3.2 on 2023-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
