# Generated by Django 3.2 on 2023-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230604_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
