# Generated by Django 3.2 on 2023-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230607_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='text',
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
